# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "http://127.0.0.1:4000" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
